### ISSUE TITLE
Análise: RF1 - RF5

### ISSUE THREAD

**Issue by GuiCT** [Team-Dire/airline-ticketing-system#1]
# Documentos de Análise
## Relacionados aos requisitos funcionais 1 até 5

Funcionalidade de AGENDAMENTO DE VOOS.

**Comment by Salies** [comment]
Caso de uso "Programar um voo", relativo aos RFs 1-5, criado.

**Comment by Salies** [comment]
Modelo conceitual refinado criado.
Caso de uso e modelo conceitual já no repositório.

Ao projetista @GuiBatalhoti: favor utilizar o mesmo arquivo `.astah` para que eu possa continuar a análise dos requisitos subsequentes a partir dele.

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Caso de uso: Programar um voo
OK.

## Modelo conceitual: 
OK.
