### ISSUE TITLE
Codificação: RF6 - RF10

### ISSUE THREAD

**Issue by GuiCT** [Team-Dire/airline-ticketing-system#14]

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Registrar um voo.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | FI | Não é possível registrar um voo em um intervalo de tempo de 30 minutos em datas diferentes. Por exemplo, após registrar um voo semanal no aeroporto ZZZZ, às 14:00 do dia 01/03/2023, não é possível registrar nenhum tipo de voo no aeroporto ZZZZ em qualquer data que esteja entre os horários das 13:30 até 14:30.  |

## Vender uma passagem.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | FI | A interface da venda de passagem exibe a mesma data de partida para todos os voos recorrentes. |
| 2 | - | IE | A interface da venda de passagem permite a venda de passagens para voos de até 31 dias da data atual. |

**Comment by G-Nozawa** [comment]
Sem defeitos encontrados
