### ISSUE TITLE
Codificação: RF11 e RF12

### ISSUE THREAD

**Issue by GuiCT** [Team-Dire/airline-ticketing-system#16]
Tinha esquecido de criar essa issue anteriormente.

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Vender uma passagem
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | FI | Passageiros com o mesmo número e tipo de identificação, mas com nomes diferentes e datas de aniversário diferentes podem ser comprar uma passagem para voo. |
| 2 | - | O | A venda de passagens não exibe o valor da passagem vendida. |

## Programa de milhas.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | FI | Passageiros com o mesmo número de identificação podem ser cadastrados e fidelizados no programa de milhas como passageiros diferentes. |

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Vender uma passagem
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | FI | Passageiros com nomes e data de nascimento diferentes mas com o mesmo número de identificação podem comprar uma passagem, contudo o sistema só armazena o primeiro passageiro que apresentar um número de identificação único. |
| 2 | - | FI | Os pontos das milhas são descontadas somente quando a decolagem do voo é confirmada e não quando a venda da passagem é feita. |

## Programa de milhas.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | FI | Caso se tente fidelizar um passageiro com um número e tipo de identificação já presente na persistência do sistema, mas com o restante dos dados errados, o sistema ainda fideliza o passageiro. |

**Comment by G-Nozawa** [comment]
Ok, sem problemas
