### ISSUE TITLE
Análise: RF6 - RF10

### ISSUE THREAD

**Issue by GuiCT** [Team-Dire/airline-ticketing-system#2]
# Documentos de Análise
## Relacionado aos requisitos funcionais 6 até 10

Funcionalidade de VENDA DE PASSAGENS AÉREAS.

**Comment by Salies** [comment]
Análise dos RF6 a 10 concluída.

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Caso de uso: Vender uma passagem
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | 7 | O | Falta mencionar se o voo comprado será de ida ou ida e volta |
| 2 | - | IE | Não seria necessário mencionar a impressão da passagem, apenas que o assento vendido se tornou ocupado.  |

## Caso de uso: Vender uma passagem
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 3 | 7 | O | Falta especificar que os voos disponíveis para realocação precisam ter um tempo mínimo de 30 minutos até o horário de partida. |

## Modelo conceitual: 
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 4 | 6 | O | Falta criar uma classe na qual represente a passagem vendida. |

**Comment by Salies** [comment]
Defeitos corrigidos na branch.
https://github.com/Team-Dire/airline-ticketing-system/tree/analise-rf6-rf10

**Comment by G-Nozawa** [comment]
OK.
