### ISSUE TITLE
Análise: RF11 e RF12

### ISSUE THREAD

**Issue by GuiCT** [Team-Dire/airline-ticketing-system#3]
# Documentos de Análise
## Relacionado ao requisitos funcionais 11 e 12

Funcionalidade de MILHAS AÉREAS e REGISTRO DE DECOLAGEM do vôo.

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Casos de uso: Vender uma passagem.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | O | Necessário informar o caso alternativo quando o passageiro com milhas suficientes não optar por um desconto. |

## Modelo conceitual:
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | O | O conceito passagem não possui os atributos de valor e desconto. |

**Comment by Salies** [comment]
### Correção: defeito 1
Ao invés de criar uma nova sequência alternativa, mofiquei a sequência típica (evento 5) para contemplar o defeito. Nela, fiz com que o sistema oferecesse uma opção sem desconto, que não usa pontos.
![image](https://user-images.githubusercontent.com/17732892/210474380-0e23e76c-1abc-46c6-9550-6e7c88943238.png)

### Correção: defeito 2
Coloquei o preço da passagem como um atributo/relação com a Clasee do voo, afinal o preço da passagem é relativo à classe. Coloquei o desconto como relativo à passagem, pois ele sim de fato é individual ao passageiro.
![image](https://user-images.githubusercontent.com/17732892/210476130-bde567fb-a8ec-4f78-af3d-267e8c7a6987.png)

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Casos de uso: Ok

## Modelo conceitual: Ok
