### ISSUE TITLE
Projeto: RF1 - RF5

### ISSUE THREAD

**Issue by GuiCT** [Team-Dire/airline-ticketing-system#4]
Elaboração dos documentos de projeto relacionados aos requisitos funcionais 1 até 5.

Funcionalidade de AGENDAMENTO DE VOOS.

**Comment by G-Nozawa** [comment]
# Lista de defeitos

## Diagrama de Comunicação
### Programar um voo
1. A classe aeroporto está recebendo informações direto do viewer, e repassa para o controlador de voo. Esse repasse de mensagens deveria ser feito por um controlador de fachada que chama um método do controlador de voo. Outra opção seria enviar as mensagens do viewer diretamente para o controlador de voo.  
2. A numeração dos métodos está incorreta. Numerar as chamadas dos métodos de maneira aninhada.

## Diagrama de Classe
1. Informar a multiplicidade das classes.
