### ISSUE TITLE
Projeto: RF11 e RF12

### ISSUE THREAD

**Issue by GuiCT** [Team-Dire/airline-ticketing-system#6]
Elaboração dos documentos de projeto relacionados aos requisitos funcionais 11 e 12.

Funcionalidade de MILHAS AÉREAS.

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Casos de uso: Vender uma passagem.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | O | O diagrama de comunicação não menciona a contabilização de descontos para quando o passageiro é um passageiro fidelizado. |
| 2 | - | FI | O diagrama de comunicação indica que um novo passageiro é sempre criado durante a compra de uma passagem. Contudo, o passageiro deveria ser primeiro buscado a fim de verificar se o passageiro já não está no sistema. |

## Casos de uso: Atestar decolagem.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | O | O diagrama de comunicação não menciona a adição de milhas para os passageiros fidelizados. |

## Diagrama de Classes:
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | - | O | Necessário implementar uma classe passagem com os valores de desconto. |
| 2 | - | O | Necessário incluir o valor da passagem para a classe "Classe". |

**Comment by GuiBatalhoti** [comment]
Correção Enviada, aguardando nova correção.

**Comment by GuiCT** [comment]
Issue fechada pelo PR #15
