### ISSUE TITLE
Inicio da codificação (RF1 à RF5)

### ISSUE THREAD

**Issue by GuiBatalhoti** [Team-Dire/airline-ticketing-system#8]
Fazer a codificação das primeiras classes: Aeroporto, ControladorVooProgramado, VooProgramado. E implementar suas respectivas funções.

Iniciar a interface juntamente com as classes inicias.

**Comment by GuiCT** [comment]
CODIFICAÇÃO

- [x] Aeroporto
- [x] ControladorVooProgramado
- [x] VooProgramado
- [x] Interface

@becelli Ir marcando cada classe assim que for feito

**Comment by GuiCT** [comment]
Já criei uma branch pra facilitar as coisas, só abrir um PR que feche essa issue.

**Comment by G-Nozawa** [comment]
# Lista de defeitos:
## Funcionalidade: Cadastrar um voo.
| Defeito | Requisito | Classe | Descrição |
|:---:|:---:|:---:|:---:|
| 1 | 4 | FI | O sistema não permite que voo de origens diferente sejam cadastrados dentro de um período de 30 minutos. A limitação de 30 minutos deveria se aplicar somente a voos de mesma origem. |
| 2 | - | FI | O sistema permite que voos de mesma origem e destino sejam cadastrados. |

**Comment by becelli** [comment]
Defeitos tratados.
